spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecoswap
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.example.com
    port: 587
    username: lungbaphe772003@example.com
    password: jiit yhyr pvua pywb
    protocol: smtp
  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000
      mailing:
        frontend:
          activation-url: http://localhost:8080/auth/activate-account
    file:
      upload:
        photos-output-path: ./upload
  server:
    port: 8080