spring:
  application:
    name: ecoswap
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 50MB
springdoc:
  default-consumes-media-type: application/json
server:
  port: 8080
  servlet:
    context-path: /api/v1/