INSERT INTO `provinces` (`id`, `name`, `name_en`, `code_name`) VALUES
                                                                   ('01', 'Hà Nội', 'Ha Noi', 'ha_noi'),
                                                                   ('02', 'Hà Giang', 'Ha Giang', 'ha_giang'),
                                                                   ('04', 'Cao Bằng', 'Cao Bang', 'cao_bang'),
                                                                   ('06', 'Bắc Kạn', 'Bac Kan', 'bac_kan'),
                                                                   ('08', 'Tuyên Quang', 'Tuyen Quang', 'tuyen_quang'),
                                                                   ('10', 'Lào Cai', 'Lao Cai', 'lao_cai'),
                                                                   ('11', 'Điện Biên', 'Dien Bien', 'dien_bien'),
                                                                   ('12', 'Lai Châu', 'Lai Chau', 'lai_chau'),
                                                                   ('14', 'Sơn La', 'Son La', 'son_la'),
                                                                   ('15', 'Yên Bái', 'Yen Bai', 'yen_bai'),
                                                                   ('17', 'Hoà Bình', 'Hoa Binh', 'hoa_binh'),
                                                                   ('19', 'Thái Nguyên', 'Thai Nguyen', 'thai_nguyen'),
                                                                   ('20', 'Lạng Sơn', 'Lang Son', 'lang_son'),
                                                                   ('22', 'Quảng Ninh', 'Quang Ninh', 'quang_ninh'),
                                                                   ('24', 'Bắc Giang', 'Bac Giang', 'bac_giang'),
                                                                   ('25', 'Phú Thọ', 'Phu Tho', 'phu_tho'),
                                                                   ('26', 'Vĩnh Phúc', 'Vinh Phuc', 'vinh_phuc'),
                                                                   ('27', 'Bắc Ninh', 'Bac Ninh', 'bac_ninh'),
                                                                   ('30', 'Hải Dương', 'Hai Duong', 'hai_duong'),
                                                                   ('31', 'Hải Phòng', 'Hai Phong', 'hai_phong'),
                                                                   ('33', 'Hưng Yên', 'Hung Yen', 'hung_yen'),
                                                                   ('34', 'Thái Bình', 'Thai Binh', 'thai_binh'),
                                                                   ('35', 'Hà Nam', 'Ha Nam', 'ha_nam'),
                                                                   ('36', 'Nam Định', 'Nam Dinh', 'nam_dinh'),
                                                                   ('37', 'Ninh Bình', 'Ninh Binh', 'ninh_binh'),
                                                                   ('38', 'Thanh Hóa', 'Thanh Hoa', 'thanh_hoa'),
                                                                   ('40', 'Nghệ An', 'Nghe An', 'nghe_an'),
                                                                   ('42', 'Hà Tĩnh', 'Ha Tinh', 'ha_tinh'),
                                                                   ('44', 'Quảng Bình', 'Quang Binh', 'quang_binh'),
                                                                   ('45', 'Quảng Trị', 'Quang Tri', 'quang_tri'),
                                                                   ('46', 'Huế', 'Hue', 'hue'),
                                                                   ('48', 'Đà Nẵng', 'Da Nang', 'da_nang'),
                                                                   ('49', 'Quảng Nam', 'Quang Nam', 'quang_nam'),
                                                                   ('51', 'Quảng Ngãi', 'Quang Ngai', 'quang_ngai'),
                                                                   ('52', 'Bình Định', 'Binh Dinh', 'binh_dinh'),
                                                                   ('54', 'Phú Yên', 'Phu Yen', 'phu_yen'),
                                                                   ('56', 'Khánh Hòa', 'Khanh Hoa', 'khanh_hoa'),
                                                                   ('58', 'Ninh Thuận', 'Ninh Thuan', 'ninh_thuan'),
                                                                   ('60', 'Bình Thuận', 'Binh Thuan', 'binh_thuan'),
                                                                   ('62', 'Kon Tum', 'Kon Tum', 'kon_tum'),
                                                                   ('64', 'Gia Lai', 'Gia Lai', 'gia_lai'),
                                                                   ('66', 'Đắk Lắk', 'Dak Lak', 'dak_lak'),
                                                                   ('67', 'Đắk Nông', 'Dak Nong', 'dak_nong'),
                                                                   ('68', 'Lâm Đồng', 'Lam Dong', 'lam_dong'),
                                                                   ('70', 'Bình Phước', 'Binh Phuoc', 'binh_phuoc'),
                                                                   ('72', 'Tây Ninh', 'Tay Ninh', 'tay_ninh'),
                                                                   ('74', 'Bình Dương', 'Binh Duong', 'binh_duong'),
                                                                   ('75', 'Đồng Nai', 'Dong Nai', 'dong_nai'),
                                                                   ('77', 'Bà Rịa - Vũng Tàu', 'Ba Ria - Vung Tau', 'ba_ria_vung_tau'),
                                                                   ('79', 'Hồ Chí Minh', 'Ho Chi Minh', 'ho_chi_minh'),
                                                                   ('80', 'Long An', 'Long An', 'long_an'),
                                                                   ('82', 'Tiền Giang', 'Tien Giang', 'tien_giang'),
                                                                   ('83', 'Bến Tre', 'Ben Tre', 'ben_tre'),
                                                                   ('84', 'Trà Vinh', 'Tra Vinh', 'tra_vinh'),
                                                                   ('86', 'Vĩnh Long', 'Vinh Long', 'vinh_long'),
                                                                   ('87', 'Đồng Tháp', 'Dong Thap', 'dong_thap'),
                                                                   ('89', 'An Giang', 'An Giang', 'an_giang'),
                                                                   ('91', 'Kiên Giang', 'Kien Giang', 'kien_giang'),
                                                                   ('92', 'Cần Thơ', 'Can Tho', 'can_tho'),
                                                                   ('93', 'Hậu Giang', 'Hau Giang', 'hau_giang'),
                                                                   ('94', 'Sóc Trăng', 'Soc Trang', 'soc_trang'),
                                                                   ('95', 'Bạc Liêu', 'Bac Lieu', 'bac_lieu'),
                                                                   ('96', 'Cà Mau', 'Ca Mau', 'ca_mau');
-- Hà Nội institutions
INSERT INTO `education_institutions` (`address`, `code`, `institution_type`, `name`, `province_id`) VALUES
                                                                                                        ('144 Xuân Thủy, Cầu Giấy, Hà Nội', 'VNU', 'UNIVERSITY', 'Đại học Quốc gia Hà Nội', '01'),
                                                                                                        ('1 Đại Cồ Việt, Hai Bà Trưng, Hà Nội', 'HUST', 'UNIVERSITY', 'Đại học Bách khoa Hà Nội', '01'),
                                                                                                        ('207 Giải Phóng, Đồng Tâm, Hai Bà Trưng, Hà Nội', 'HMU', 'UNIVERSITY', 'Đại học Y Hà Nội', '01'),
                                                                                                        ('334 Nguyễn Trãi, Thanh Xuân, Hà Nội', 'NEU', 'UNIVERSITY', 'Đại học Kinh tế Quốc dân', '01'),
                                                                                                        ('144 Xuân Thủy, Cầu Giấy, Hà Nội', 'USSH', 'UNIVERSITY', 'Đại học Khoa học Xã hội và Nhân văn - ĐHQGHN', '01'),
                                                                                                        ('19 Lê Thánh Tông, Hoàn Kiếm, Hà Nội', 'ULIS', 'UNIVERSITY', 'Đại học Ngoại ngữ - ĐHQGHN', '01'),
                                                                                                        ('Đường Phạm Văn Đồng, Cầu Giấy, Hà Nội', 'UET', 'UNIVERSITY', 'Đại học Công nghệ - ĐHQGHN', '01'),
                                                                                                        ('175 Tây Sơn, Đống Đa, Hà Nội', 'HANU', 'UNIVERSITY', 'Đại học Hà Nội', '01'),
                                                                                                        ('Km9 Nguyễn Trãi, Thanh Xuân, Hà Nội', 'HNUE', 'UNIVERSITY', 'Đại học Sư phạm Hà Nội', '01'),
                                                                                                        ('Số 1 Phạm Văn Đồng, Cầu Giấy, Hà Nội', 'PTIT', 'UNIVERSITY', 'Học viện Công nghệ Bưu chính Viễn thông', '01'),
                                                                                                        ('Hà Đông, Hà Nội', 'YHCM', 'UNIVERSITY', 'Học viện Y Dược học Cổ truyền Việt Nam', '01'),
                                                                                                        ('236B Lê Duẩn, Đống Đa, Hà Nội', 'HVNH', 'UNIVERSITY', 'Học viện Ngân hàng', '01'),
                                                                                                        ('77 Nguyễn Chí Thanh, Đống Đa, Hà Nội', 'HLU', 'UNIVERSITY', 'Đại học Luật Hà Nội', '01'),
                                                                                                        ('298 Đường Cầu Diễn, Bắc Từ Liêm, Hà Nội', 'HVKTQS', 'UNIVERSITY', 'Học viện Kỹ thuật Quân sự', '01'),
                                                                                                        ('101 Tô Hiệu, Cầu Giấy, Hà Nội', 'HUMG', 'UNIVERSITY', 'Đại học Mỏ - Địa chất', '01'),

-- Đà Nẵng institutions
                                                                                                        ('41 Lê Duẩn, Hải Châu, Đà Nẵng', 'UDA', 'UNIVERSITY', 'Đại học Đà Nẵng', '48'),
                                                                                                        ('54 Nguyễn Lương Bằng, Liên Chiểu, Đà Nẵng', 'DUT', 'UNIVERSITY', 'Đại học Bách khoa - Đại học Đà Nẵng', '48'),
                                                                                                        ('459 Tôn Đức Thắng, Liên Chiểu, Đà Nẵng', 'UED', 'UNIVERSITY', 'Đại học Sư phạm - Đại học Đà Nẵng', '48'),
                                                                                                        ('131 Lương Nhữ Hộc, Cẩm Lệ, Đà Nẵng', 'DUE', 'UNIVERSITY', 'Đại học Kinh tế - Đại học Đà Nẵng', '48'),
                                                                                                        ('41 Lê Duẩn, Hải Châu, Đà Nẵng', 'UDN', 'UNIVERSITY', 'Đại học Ngoại ngữ - Đại học Đà Nẵng', '48'),
                                                                                                        ('470 Trần Đại Nghĩa, Ngũ Hành Sơn, Đà Nẵng', 'DTC', 'COLLEGE', 'Cao đẳng Công nghệ - Đại học Đà Nẵng', '48'),
                                                                                                        ('280 Trần Hưng Đạo, Sơn Trà, Đà Nẵng', 'DCC', 'COLLEGE', 'Cao đẳng Công nghệ Thông tin', '48'),
                                                                                                        ('17 Tạ Quang Bửu, Sơn Trà, Đà Nẵng', 'DAC', 'COLLEGE', 'Cao đẳng Du lịch Đà Nẵng', '48'),
                                                                                                        ('48 Cao Thắng, Hải Châu, Đà Nẵng', 'DMC', 'COLLEGE', 'Cao đẳng Y tế Đà Nẵng', '48'),

-- TP.HCM institutions (including Làng Đại học Thủ Đức)
                                                                                                        ('Linh Trung, Thủ Đức, TP.HCM', 'VNUHCM', 'UNIVERSITY', 'Đại học Quốc gia TP.HCM', '79'),
                                                                                                        ('268 Lý Thường Kiệt, Quận 10, TP.HCM', 'HCMUT', 'UNIVERSITY', 'Đại học Bách Khoa - ĐHQG TP.HCM', '79'),
                                                                                                        ('227 Nguyễn Văn Cừ, Quận 5, TP.HCM', 'UIT', 'UNIVERSITY', 'Đại học Công nghệ Thông tin - ĐHQG TP.HCM', '79'),
                                                                                                        ('227 Nguyễn Văn Cừ, Quận 5, TP.HCM', 'HCMUS', 'UNIVERSITY', 'Đại học Khoa học Tự nhiên - ĐHQG TP.HCM', '79'),
                                                                                                        ('10-12 Đinh Tiên Hoàng, Quận 1, TP.HCM', 'USSH', 'UNIVERSITY', 'Đại học Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM', '79'),
                                                                                                        ('Khu phố 6, Linh Trung, Thủ Đức, TP.HCM', 'UI', 'UNIVERSITY', 'Đại học Quốc tế - ĐHQG TP.HCM', '79'),
                                                                                                        ('Khu phố 6, Linh Trung, Thủ Đức, TP.HCM', 'UEL', 'UNIVERSITY', 'Đại học Kinh tế - Luật - ĐHQG TP.HCM', '79'),
                                                                                                        ('1 Võ Văn Ngân, Thủ Đức, TP.HCM', 'HCMUTE', 'UNIVERSITY', 'Đại học Sư phạm Kỹ thuật TP.HCM', '79'),
                                                                                                        ('Khu phố 6, P. Linh Trung, Thủ Đức', 'TTU', 'UNIVERSITY', 'Đại học Tôn Đức Thắng', '79'),
                                                                                                        ('Đường Man Thiện, Thủ Đức', 'FPTU', 'UNIVERSITY', 'Đại học FPT TP.HCM', '79'),
                                                                                                        ('273 An Dương Vương, Quận 5, TP.HCM', 'YD', 'UNIVERSITY', 'Đại học Y Dược TP.HCM', '79'),
                                                                                                        ('217 Hồng Bàng, Quận 5, TP.HCM', 'YDCT', 'UNIVERSITY', 'Đại học Y khoa Phạm Ngọc Thạch', '79'),
                                                                                                        ('35-37 Hồ Hảo Hớn, Quận 1, TP.HCM', 'HUFI', 'UNIVERSITY', 'Đại học Công nghiệp Thực phẩm TP.HCM', '79'),
                                                                                                        ('475A Điện Biên Phủ, Quận Bình Thạnh, TP.HCM', 'FTU2', 'UNIVERSITY', 'Đại học Ngoại thương - Cơ sở phía Nam', '79'),
                                                                                                        ('778 Nguyễn Kiệm, Quận Phú Nhuận, TP.HCM', 'HOA SEN', 'UNIVERSITY', 'Đại học Hoa Sen', '79'),
                                                                                                        ('232/2 Võ Thị Sáu, Quận 3, TP.HCM', 'RMIT', 'UNIVERSITY', 'Đại học RMIT Việt Nam', '79'),
                                                                                                        ('391A Nam Kỳ Khởi Nghĩa, Quận 3, TP.HCM', 'SGU', 'UNIVERSITY', 'Đại học Sài Gòn', '79'),
                                                                                                        ('12 Nguyễn Văn Bảo, Gò Vấp, TP.HCM', 'IUH', 'UNIVERSITY', 'Đại học Công nghiệp TP.HCM', '79'),
                                                                                                        ('3/2, Quận 10, TP.HCM', 'UEH', 'UNIVERSITY', 'Đại học Kinh tế TP.HCM', '79'),
                                                                                                        ('140 Lê Trọng Tấn, Tân Phú, TP.HCM', 'TDC', 'COLLEGE', 'Cao đẳng Kinh tế Đối ngoại', '79'),
                                                                                                        ('215 Nguyễn Văn Luông, Quận 6, TP.HCM', 'SPT', 'COLLEGE', 'Cao đẳng Sư phạm Trung ương TP.HCM', '79'),
                                                                                                        ('502 Đỗ Xuân Hợp, Quận 9, TP.HCM', 'SPK', 'COLLEGE', 'Cao đẳng Sư phạm Kỹ thuật Vĩnh Long', '79'),
                                                                                                        ('33 Vĩnh Viễn, Quận 10, TP.HCM', 'YDC', 'COLLEGE', 'Cao đẳng Y Dược TP.HCM', '79'),
                                                                                                        ('Khu phố 6, Linh Trung, Thủ Đức, TP.HCM', 'NLU', 'UNIVERSITY', 'Đại học Nông Lâm TP.HCM', '79');