spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eswap
    username: root
    password: pblues_eswap
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lungbaphe772003@gmail.com
    password: jiit yhyr pvua pywb
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000
        refresh-token:
          expiration: 604800000
    file:
      upload:
        media-output-path: ./media
  server:
    port: 8080
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 3000ms
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: post-group
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      transactional-id-prefix: eswap-producer-
      acks: all
      retries: 3
      properties:
        request.timeout.ms: 30000
        retry.backoff.ms: 1000
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    org:
      springframework:
        web: DEBUG
